import React from 'react';
import { SelectionHover } from '../lib/selection_hover.js';
import { isKeyMoveNode } from '../lib/dom_tree.js';
import { MODAL_CHANGED_EVENT } from '../lib/modal_context.js';

export default function useSelectionHover() {
  const [hover] = React.useState(() => new SelectionHover());
  React.useEffect(() => {
    const reconcile = () => hover.reconcile();
    const pointer = (event: PointerEvent) => {
      const target = event.composedPath()[0];
      if (event.isTrusted && target instanceof Node && !isKeyMoveNode(target))
        hover.releaseTo(target instanceof Element ? target : null);
    };
    // Real mouse interaction takes over; events generated by this feature do not.
    document.addEventListener('pointermove', pointer, true);
    document.addEventListener('pointerdown', pointer, true);
    document.addEventListener(MODAL_CHANGED_EVENT, reconcile);
    return () => {
      document.removeEventListener('pointermove', pointer, true);
      document.removeEventListener('pointerdown', pointer, true);
      document.removeEventListener(MODAL_CHANGED_EVENT, reconcile);
      hover.clear();
    };
  }, [hover]);
  return hover;
}
